### PR TITLE
Update ci.yml

### PR DESCRIPTION
**Pull request by rodabt**
Changed oauth.v to auth.v

### CODE REVIEW

**Comment by ArtemkaKun** [comment]
Hi, isn't this the same as #66 ? If yes - this one should be closed I think

**Comment by rodabt** [comment]
> Hi, isn't this the same as #66 ? If yes - this one should be closed I think

Not exactly, in this one, there is another file mentioned that is missing: mod.v

**Comment by rodabt** [comment]
There are 2 commits accumulated with almost the same information because the ci process is not working, and checks are not passing...

**Comment by ArtemkaKun** [comment]
I think we should check formatting for all files on the repo, not just selected one. The problem is that the CI will not pass after this change because code need to be cleaned up first

**Pull request merged**
